// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class writer_update_imageformat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(writer_update_imageformat));
        
        string IMigrationMetadata.Id
        {
            get { return "202305121246137_writer_update_imageformat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
