// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class imagefiles_add_remove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imagefiles_add_remove));
        
        string IMigrationMetadata.Id
        {
            get { return "202305171650165_imagefiles_add_remove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
